name: Update PDFs
on:
  workflow_dispatch: # manual trigger
  push:
      branches: [ main ]
      paths: # auto trigger on changes to these paths
        - 'src/**'
        - 'public/**'
        - 'data/**'
        - '.github/**'

jobs:
  update-pdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm' # enable npm cache

      - name: Install Puppeteer
        run: | # prevent updates to package.json
          npm install puppeteer@latest --no-save
          npm install @types/puppeteer@latest --no-save

      - name: Generate PDFs
        id: generate_pdfs
        run: |
          node .github/scripts/generate-pdfs.js
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}

      - name: Check PDF generation
        run: |
          echo "Checking pdfs directory contents:"
          ls -la pdfs/
          if [ ! -d "pdfs" ] || [ -z "$(ls -A pdfs/)" ]; then
            echo "Error: PDFs were not generated correctly"
            exit 1
          fi

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          echo "Git status before add:"
          git status

          git add pdfs/ # only add pdfs directory

          echo "Git status after add:"
          git status

          # check for unexpected changes outside pdfs/
          UNEXPECTED_CHANGES=$(git diff --name-only --diff-filter=M | grep -v '^pdfs/' || true)
          if [ -n "$UNEXPECTED_CHANGES" ]; then
            echo "❌ Unexpected changes detected outside pdfs/:"
            echo "$UNEXPECTED_CHANGES"
            echo "🚨 Exiting to prevent unintended commits."
            exit 1
          fi

          # commit only if there are changes in pdfs/
          if git diff --staged --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "Update PDFs [skip ci]"
            git push
          fi